name: Build and Release Python Executable

on:
  push:
    branches:
      - main  # Mude para a branch desejada
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout o repositório
    - name: Checkout code
      uses: actions/checkout@v3

    # Configurar Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Especifique a versão do Python

    # Instalar dependências do projeto
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Instalar PyInstaller para compilar o executável
    - name: Install PyInstaller
      run: |
        pip install pyinstaller

    # Compilar o executável usando PyInstaller
    - name: Build executable
      run: |
        pyinstaller --noconfirm --onefile --windowed --icon "./fk-logo.ico" "./pedidosAtraso.py"

    # Publicar o executável como uma release no GitHub
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        release_name: Release ${{ github.run_number }}
        draft: false
        prerelease: false

    # Upload do executável gerado para a release
    - name: Upload executable to release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: output/main.exe  # Substitua pelo caminho do arquivo gerado
        asset_name: main.exe  # Nome do arquivo executável
        asset_content_type: application/octet-stream
